# Generated by Django 6.0 on 2025-12-18 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_alter_contactmessage_created_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactMessage',
            new_name='dataFormModels',
        ),
        migrations.RenameField(
            model_name='dataformmodels',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='dataformmodels',
            old_name='is_read',
            new_name='isRead',
        ),
    ]
