# Generated by Django 6.0 on 2025-12-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagemcontato',
            name='empresa',
            field=models.CharField(default='Não informada', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mensagemcontato',
            name='telefone',
            field=models.CharField(default='0000-0000', max_length=20),
            preserve_default=False,
        ),
    ]
