# Generated by Django 6.0 on 2025-12-19 18:47

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0002_mensagemcontato_empresa_mensagemcontato_telefone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensagemcontato',
            old_name='lido',
            new_name='lida',
        ),
        migrations.AlterField(
            model_name='mensagemcontato',
            name='empresa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mensagemcontato',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
