# Generated by Django 6.0 on 2025-12-16 19:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Envio')),
                ('read', models.BooleanField(default=False, verbose_name='Lido')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['read'], name='mainapp_mes_read_104d46_idx'), models.Index(fields=['-sent_at'], name='mainapp_mes_sent_at_1cfb81_idx')],
            },
        ),
    ]
