# Generated by Django 6.0 on 2025-12-25 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mensagem',
            new_name='Message',
        ),
    ]
