# Generated by Django 6.0 on 2025-12-16 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('data_envio', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('lido', models.BooleanField(default=False, verbose_name='Lido')),
            ],
            options={
                'verbose_name': 'Messagem',
                'verbose_name_plural': 'Messagens',
                'ordering': ['-data_envio'],
            },
        ),
    ]
