# Generated by Django 6.0 on 2025-12-16 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casulo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Mensagem',
        ),
    ]
