# Generated by Django 6.0 on 2025-12-18 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casulo', '0002_rename_message_mensagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('name', models.CharField(max_length=80, verbose_name='Nome')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Categoria de serviço',
                'verbose_name_plural': 'Categorias de serviço',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('title', models.CharField(max_length=120, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('icon', models.CharField(choices=[('hand', 'Hand'), ('baby', 'Baby'), ('heart', 'Heart'), ('moon', 'Moon'), ('brain', 'Brain'), ('stethoscope', 'Stethoscope'), ('bone', 'Bone'), ('mic', 'Mic'), ('users', 'Users'), ('zap', 'Zap'), ('apple', 'Apple'), ('activity', 'Activity')], default='stethoscope', max_length=20, verbose_name='Ícone')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='casulo.servicecategory', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['order', 'title'],
            },
        ),
    ]
