# Generated by Django 6.0 on 2025-12-22 14:04

import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casulo', '0003_servicecategory_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('cargo', models.CharField(max_length=120, verbose_name='Cargo')),
                ('registro', models.CharField(blank=True, max_length=120, verbose_name='Registro')),
                ('bio', models.TextField(blank=True, verbose_name='Bio')),
                ('tags', models.CharField(blank=True, help_text='Separe por vírgula. Ex: Infantil, Adulto, Online, Ansiedade', max_length=255, verbose_name='Tags')),
                ('foto', stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='team/', variations={'thumb': (160, 160, True)}, verbose_name='Foto')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Profissional',
                'verbose_name_plural': 'Equipe',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='mensagem',
            options={'ordering': ['-data_envio'], 'verbose_name': 'Mensagem', 'verbose_name_plural': 'Mensagens'},
        ),
    ]
